-- MySQL Script generated by MySQL Workbench
-- Tue Jul 15 09:50:14 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleados` (
  `idEmpleados` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(60) NOT NULL,
  `ApellidoP` VARCHAR(45) NOT NULL,
  `ApellidoM` VARCHAR(45) NULL,
  `FechaNacimiento` DATE NULL,
  `Telefono` VARCHAR(45) NULL,
  `Direccion` VARCHAR(100) NULL,
  `Puesto` VARCHAR(45) NULL,
  `AreaTrabajo` VARCHAR(100) NULL,
  PRIMARY KEY (`idEmpleados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedores` (
  `idProveedores` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`idProveedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categorias` (
  `idCategorias` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idCategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subcategorias` (
  `idSubcategorias` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL,
  `Fk_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idSubcategorias`),
  INDEX `fk_subCategoria_Categoria_idx` (`Fk_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_subCategoria_Categoria`
    FOREIGN KEY (`Fk_idCategoria`)
    REFERENCES `mydb`.`Categorias` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `NombreUsuario` VARCHAR(30) NULL,
  `Contraseña` VARCHAR(20) NULL,
  `NombreCompleto` VARCHAR(60) NULL,
  `Rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Articulos` (
  `idArticulos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL,
  `Marca` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  `Color` VARCHAR(45) NULL,
  `Estado` TINYINT NULL,
  `Descripcion` VARCHAR(200) NULL,
  `Fk_idCategoria` INT NOT NULL,
  `Fk_idsubcategoria` INT NOT NULL,
  `Fk_idProveedor` INT NOT NULL,
  `Fk_UsuarioAlta` INT NOT NULL,
  PRIMARY KEY (`idArticulos`),
  INDEX `fk_Articulo_Categoria1_idx` (`Fk_idCategoria` ASC) VISIBLE,
  INDEX `fk_Articulo_subCategoria1_idx` (`Fk_idsubcategoria` ASC) VISIBLE,
  INDEX `fk_Articulo_Proveedor1_idx` (`Fk_idProveedor` ASC) VISIBLE,
  INDEX `fk_Articulo_Usuarios1_idx` (`Fk_UsuarioAlta` ASC) VISIBLE,
  CONSTRAINT `fk_Articulo_Categoria1`
    FOREIGN KEY (`Fk_idCategoria`)
    REFERENCES `mydb`.`Categorias` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articulo_subCategoria1`
    FOREIGN KEY (`Fk_idsubcategoria`)
    REFERENCES `mydb`.`subcategorias` (`idSubcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articulo_Proveedor1`
    FOREIGN KEY (`Fk_idProveedor`)
    REFERENCES `mydb`.`Proveedores` (`idProveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articulo_Usuarios1`
    FOREIGN KEY (`Fk_UsuarioAlta`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Resguardos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Resguardos` (
  `idResguardos` INT NOT NULL AUTO_INCREMENT,
  `NoSerie` VARCHAR(45) NULL,
  `DescripcionGeneral` VARCHAR(200) NULL,
  `EstadoGeneral` VARCHAR(200) NULL,
  `UbicacionResguardo` VARCHAR(200) NULL,
  `Fk_idArticulo` INT NOT NULL,
  `Fk_idEmpleado` INT NOT NULL,
  `Fk_UsuarioAlta` INT NOT NULL,
  PRIMARY KEY (`idResguardos`),
  INDEX `fk_Inventario_Articulo1_idx` (`Fk_idArticulo` ASC) VISIBLE,
  INDEX `fk_Inventario_Empleado1_idx` (`Fk_idEmpleado` ASC) VISIBLE,
  INDEX `fk_Resguardos_Usuarios1_idx` (`Fk_UsuarioAlta` ASC) VISIBLE,
  CONSTRAINT `fk_Inventario_Articulo1`
    FOREIGN KEY (`Fk_idArticulo`)
    REFERENCES `mydb`.`Articulos` (`idArticulos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Empleado1`
    FOREIGN KEY (`Fk_idEmpleado`)
    REFERENCES `mydb`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resguardos_Usuarios1`
    FOREIGN KEY (`Fk_UsuarioAlta`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prestamos` (
  `idPrestamos` INT NOT NULL AUTO_INCREMENT,
  `UbicacionOrigen` VARCHAR(100) NULL,
  `UbicacionDestino` VARCHAR(100) NULL,
  `Estado` VARCHAR(100) NOT NULL,
  `FechaPrestamo` DATETIME NOT NULL,
  `FechaDevolucion` DATETIME NULL,
  `FechaEstimadaDevolucion` DATETIME NULL,
  `Fk_EmpleadoOrigen` INT NOT NULL,
  `Fk_EmpleadoDestino` INT NOT NULL,
  `Esmantenimiento` TINYINT NULL,
  `Fk_idProveedor` INT NOT NULL,
  `Fk_UsuarioResponsable` INT NOT NULL,
  PRIMARY KEY (`idPrestamos`),
  INDEX `fk_Prestamo_Empleado1_idx` (`Fk_EmpleadoOrigen` ASC) VISIBLE,
  INDEX `fk_Prestamo_Empleado2_idx` (`Fk_EmpleadoDestino` ASC) VISIBLE,
  INDEX `fk_Prestamo_Proveedor1_idx` (`Fk_idProveedor` ASC) VISIBLE,
  INDEX `fk_Prestamo_Usuarios1_idx` (`Fk_UsuarioResponsable` ASC) VISIBLE,
  CONSTRAINT `fk_Prestamo_Empleado1`
    FOREIGN KEY (`Fk_EmpleadoOrigen`)
    REFERENCES `mydb`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Empleado2`
    FOREIGN KEY (`Fk_EmpleadoDestino`)
    REFERENCES `mydb`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Proveedor1`
    FOREIGN KEY (`Fk_idProveedor`)
    REFERENCES `mydb`.`Proveedores` (`idProveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Usuarios1`
    FOREIGN KEY (`Fk_UsuarioResponsable`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ArticulosPrestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ArticulosPrestamo` (
  `idArticulosPrestamo` INT NOT NULL AUTO_INCREMENT,
  `Fk_Prestamo` INT NOT NULL,
  `Fk_idInventario` INT NOT NULL,
  `Estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idArticulosPrestamo`),
  INDEX `fk_ArticulosPrestamo_Prestamo1_idx` (`Fk_Prestamo` ASC) VISIBLE,
  INDEX `fk_ArticulosPrestamo_Inventario1_idx` (`Fk_idInventario` ASC) VISIBLE,
  CONSTRAINT `fk_ArticulosPrestamo_Prestamo1`
    FOREIGN KEY (`Fk_Prestamo`)
    REFERENCES `mydb`.`Prestamos` (`idPrestamos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ArticulosPrestamo_Inventario1`
    FOREIGN KEY (`Fk_idInventario`)
    REFERENCES `mydb`.`Resguardos` (`idResguardos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historial` (
  `idHistorial` INT NOT NULL AUTO_INCREMENT,
  `Tipo evento` VARCHAR(15) NULL,
  `FechaEvento` DATE NULL,
  `Tabla Afectada` VARCHAR(20) NULL,
  `IdReferencia` INT NULL,
  `Fk_UsuarioResponsable` INT NOT NULL,
  PRIMARY KEY (`idHistorial`),
  INDEX `Usuario responsable_idx` (`Fk_UsuarioResponsable` ASC) VISIBLE,
  CONSTRAINT `Usuario responsable`
    FOREIGN KEY (`Fk_UsuarioResponsable`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
